services:
  - type: web
    name: feedforwarder-web
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
    healthCheckPath: /healthz
    plan: free
    autoDeploy: true
    